import datetime
from typing import Optional

from sqlalchemy import Boolean, Date, ForeignKey, Numeric, String
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.database import Base


class User(Base):
    __tablename__ = "users"

    id: Mapped[int] = mapped_column(primary_key=True)
    email: Mapped[str] = mapped_column(String(255), unique=True, index=True)
    hashed_password: Mapped[str] = mapped_column(String(255))
    created_at: Mapped[datetime.datetime] = mapped_column(default=datetime.datetime.utcnow)

    # A 7-digit account number assigned at signup -- lets someone be added to a
    # share/split by a short number instead of having to hand out their email.
    # Generated with a uniqueness check (see auth.generate_unique_user_number),
    # not a DB-level constraint, since sqlite can't add one via ALTER TABLE to
    # an already-existing column.
    user_number: Mapped[str] = mapped_column(String(7), index=True)
    # Display name the user sets for themselves (e.g. "Lexy Hoffend") -- shown
    # in place of their email wherever they're identified to someone else
    # (sharing, splitting). Null until they set one, in which case email is
    # still the fallback.
    name: Mapped[Optional[str]] = mapped_column(String(255), nullable=True, default=None)

    # Record of agreeing to the Terms of Service and Privacy Policy: when, and
    # which version (app.legal.CURRENT_TERMS_VERSION at the time). Null for
    # accounts created before the policies existed until they accept. Added
    # to existing databases by app.main._add_missing_columns.
    terms_accepted_at: Mapped[Optional[datetime.datetime]] = mapped_column(nullable=True, default=None)
    terms_version: Mapped[Optional[str]] = mapped_column(String(20), nullable=True, default=None)

    # How Payment Cycles get created for this user. Null means "hasn't chosen yet" --
    # gates the user into the /setup-cycle picker on their next login. "custom" means
    # fully manual creation (today's original behavior); the other three modes are
    # auto-generated by ensure_upcoming_periods(). Only one of the two anchor fields
    # is populated, depending on mode: pay_cycle_anchor_day for "monthly" (a day-of-month
    # that must survive indefinitely), pay_cycle_anchor_date for "weekly"/"biweekly"
    # (a specific date used as the +7/+14 step's base).
    pay_cycle_mode: Mapped[Optional[str]] = mapped_column(String(20), nullable=True, default=None)
    pay_cycle_anchor_day: Mapped[Optional[int]] = mapped_column(nullable=True, default=None)
    pay_cycle_anchor_date: Mapped[Optional[datetime.date]] = mapped_column(Date, nullable=True, default=None)
    # Second pay day of the month for "semimonthly" (first is pay_cycle_anchor_day),
    # e.g. 15 and 31 -- 31 clamps to the month's last day.
    pay_cycle_anchor_day2: Mapped[Optional[int]] = mapped_column(nullable=True, default=None)
    # How auto-generated cycles are laid out. "payday" (current): each cycle
    # STARTS on a payday and runs to the day before the next one, so its bills
    # are the ones that paycheck actually pays. Null = legacy layout (cycles
    # END on the payday); ensure_upcoming_periods switches those accounts over
    # once, leaving existing cycles untouched -- see _switch_to_payday_layout.
    cycle_layout: Mapped[Optional[str]] = mapped_column(String(10), nullable=True, default=None)


    @property
    def needs_terms(self) -> bool:
        from app.legal import CURRENT_TERMS_VERSION

        return self.terms_version != CURRENT_TERMS_VERSION


class IncomeSource(Base):
    """A recurring 'Payment Cycle' -- a job's paycheck, rental income, etc.
    Only truly recurring income lives here; one-off amounts are ad-hoc
    IncomeEntry rows with no source (see IncomeEntry.custom_label)."""

    __tablename__ = "income_sources"

    id: Mapped[int] = mapped_column(primary_key=True)
    user_id: Mapped[int] = mapped_column(ForeignKey("users.id"), index=True)
    name: Mapped[str] = mapped_column(String(255))  # e.g. "Labcorp", "Rent Received"
    cadence_type: Mapped[str] = mapped_column(String(20))  # monthly_date | weekly | biweekly
    cadence_day_of_month: Mapped[Optional[int]] = mapped_column(nullable=True)  # 1-31, monthly_date only
    cadence_weekday: Mapped[Optional[int]] = mapped_column(nullable=True)  # 0=Mon..6=Sun, weekly/biweekly only
    cadence_day_of_month2: Mapped[Optional[int]] = mapped_column(nullable=True, default=None)  # semimonthly second day
    start_date: Mapped[datetime.date] = mapped_column(Date)  # anchor date; cadence begins here
    amount: Mapped[float] = mapped_column(Numeric(10, 2), default=0)  # positive, per occurrence
    active: Mapped[bool] = mapped_column(Boolean, default=True)

    entries: Mapped[list["IncomeEntry"]] = relationship(back_populates="source")


class BillSource(Base):
    __tablename__ = "bill_sources"

    id: Mapped[int] = mapped_column(primary_key=True)
    user_id: Mapped[int] = mapped_column(ForeignKey("users.id"), index=True)
    name: Mapped[str] = mapped_column(String(255))  # e.g. "Mortgage 1", "AMEX", or custom name if category="Other"
    category: Mapped[str] = mapped_column(String(50), default="Other")  # e.g. "Energy", "Internet", "Other"
    default_target_amount: Mapped[float] = mapped_column(Numeric(10, 2), default=0)
    is_revolving: Mapped[bool] = mapped_column(Boolean, default=False)  # true for credit cards
    active: Mapped[bool] = mapped_column(Boolean, default=True)
    # Dependent picklist, only meaningful when category="Credit Card" -- which issuer/
    # network this specific card is, so multiple cards can be tracked individually
    # while still rolling up into one "Credit Card" category for analysis.
    credit_card_issuer: Mapped[Optional[str]] = mapped_column(String(50), nullable=True, default=None)
    # Day of month (1-31) this bill is actually due, independent of the pay-cycle
    # schedule -- e.g. rent due on the 1st regardless of when the paycheck lands.
    due_day: Mapped[Optional[int]] = mapped_column(nullable=True, default=None)
    # When true, and this bill is shared with one or more people (see SharedAccess),
    # its amount is divided evenly across the owner plus everyone it's shared with,
    # rather than each person seeing/owing the full amount.
    split_shared: Mapped[bool] = mapped_column(Boolean, default=False)
    # Set only on an auto-provisioned "reimbursement" bill living in a VIEWER's
    # own account -- points back at the specific SharedAccessBill link it was
    # derived from. Lets the viewer track "have I paid my split share back to
    # the owner" as their own bill, independent of whether the owner has paid
    # the real bill. Null for every bill someone actually created themselves.
    shared_access_bill_id: Mapped[Optional[int]] = mapped_column(
        ForeignKey("shared_access_bills.id"), nullable=True, default=None
    )

    entries: Mapped[list["BillEntry"]] = relationship(back_populates="source")


class PayPeriod(Base):
    __tablename__ = "pay_periods"

    id: Mapped[int] = mapped_column(primary_key=True)
    user_id: Mapped[int] = mapped_column(ForeignKey("users.id"), index=True)
    label: Mapped[str] = mapped_column(String(255))  # e.g. "PayStub 6/26/26"
    start_date: Mapped[datetime.date] = mapped_column(Date)
    end_date: Mapped[datetime.date] = mapped_column(Date)
    # The payday this cycle belongs to. Payday-layout cycles: start_date.
    # Legacy cycles: end_date (backfilled on startup). A "bridge" cycle created
    # when an account switches layouts shares its pay_date with the legacy cycle
    # before it, since the same paycheck funds both -- periods sharing a
    # pay_date form one paycheck group (see period_service.paycheck_group).
    pay_date: Mapped[Optional[datetime.date]] = mapped_column(Date, nullable=True, default=None)

    # "Manage My Pay Cycle" plan for this paycheck (bills' planned amounts live
    # on BillEntry). Null = not set yet.
    plan_future_amount: Mapped[Optional[float]] = mapped_column(Numeric(10, 2), nullable=True, default=None)
    plan_future_bucket_id: Mapped[Optional[int]] = mapped_column(nullable=True, default=None)
    plan_fun_amount: Mapped[Optional[float]] = mapped_column(Numeric(10, 2), nullable=True, default=None)
    managed_at: Mapped[Optional[datetime.datetime]] = mapped_column(nullable=True, default=None)

    # Explicit order_by: without it Postgres returns rows in physical order, and
    # an UPDATE rewrites the row elsewhere -- so checking an item off would
    # make it jump to a different spot in the list.
    income_entries: Mapped[list["IncomeEntry"]] = relationship(
        back_populates="period", cascade="all, delete-orphan", order_by="IncomeEntry.id"
    )
    bill_entries: Mapped[list["BillEntry"]] = relationship(
        back_populates="period", cascade="all, delete-orphan", order_by="BillEntry.id"
    )
    savings_entries: Mapped[list["SavingsEntry"]] = relationship(
        back_populates="period", cascade="all, delete-orphan", order_by="SavingsEntry.id"
    )


class IncomeEntry(Base):
    __tablename__ = "income_entries"

    id: Mapped[int] = mapped_column(primary_key=True)
    period_id: Mapped[int] = mapped_column(ForeignKey("pay_periods.id"))
    income_source_id: Mapped[Optional[int]] = mapped_column(ForeignKey("income_sources.id"), nullable=True)
    custom_label: Mapped[Optional[str]] = mapped_column(String(255), nullable=True)  # set when income_source_id is null (one-time income)
    expected_amount: Mapped[float] = mapped_column(Numeric(10, 2), default=0)
    actual_amount: Mapped[float] = mapped_column(Numeric(10, 2), default=0)
    is_received: Mapped[bool] = mapped_column(default=False)

    period: Mapped["PayPeriod"] = relationship(back_populates="income_entries")
    source: Mapped[Optional["IncomeSource"]] = relationship(back_populates="entries")


class BillEntry(Base):
    __tablename__ = "bill_entries"

    id: Mapped[int] = mapped_column(primary_key=True)
    period_id: Mapped[int] = mapped_column(ForeignKey("pay_periods.id"))
    bill_source_id: Mapped[int] = mapped_column(ForeignKey("bill_sources.id"))
    target_amount: Mapped[float] = mapped_column(Numeric(10, 2), default=0)
    actual_amount: Mapped[float] = mapped_column(Numeric(10, 2), default=0)
    is_paid: Mapped[bool] = mapped_column(default=False)
    # Plan for this paycheck: how much of this bill it pays (null = the
    # default, see period_service.default_planned_amount) and how much is
    # pushed to the next paycheck (moved or split).
    planned_amount: Mapped[Optional[float]] = mapped_column(Numeric(10, 2), nullable=True, default=None)
    deferred_amount: Mapped[float] = mapped_column(Numeric(10, 2), default=0)

    period: Mapped["PayPeriod"] = relationship(back_populates="bill_entries")
    source: Mapped["BillSource"] = relationship(back_populates="entries")


class SharedAccess(Base):
    """A grant of read-only visibility from `owner` over a chosen subset of
    their bill and income sources, to whoever logs in with `viewer_email`.
    There's no invite/email-sending flow -- the app has no outbound email --
    so the relationship simply activates the moment an account with that
    email exists and looks at their own "Shared with me" view."""

    __tablename__ = "shared_access"

    id: Mapped[int] = mapped_column(primary_key=True)
    owner_id: Mapped[int] = mapped_column(ForeignKey("users.id"), index=True)
    viewer_email: Mapped[str] = mapped_column(String(255), index=True)
    label: Mapped[Optional[str]] = mapped_column(String(255), nullable=True)  # e.g. "Mom", optional

    shared_bills: Mapped[list["SharedAccessBill"]] = relationship(
        back_populates="shared_access", cascade="all, delete-orphan"
    )
    shared_income: Mapped[list["SharedAccessIncome"]] = relationship(
        back_populates="shared_access", cascade="all, delete-orphan"
    )


class SharedAccessBill(Base):
    __tablename__ = "shared_access_bills"

    id: Mapped[int] = mapped_column(primary_key=True)
    shared_access_id: Mapped[int] = mapped_column(ForeignKey("shared_access.id"), index=True)
    bill_source_id: Mapped[int] = mapped_column(ForeignKey("bill_sources.id"))

    shared_access: Mapped["SharedAccess"] = relationship(back_populates="shared_bills")
    # Explicit foreign_keys needed -- BillSource.shared_access_bill_id creates a
    # second FK path between these two tables (for the reverse "which share did
    # this derived reimbursement bill come from" link), so SQLAlchemy can no
    # longer infer which column this relationship should join on.
    bill_source: Mapped["BillSource"] = relationship(foreign_keys=[bill_source_id])


class SharedAccessIncome(Base):
    __tablename__ = "shared_access_income"

    id: Mapped[int] = mapped_column(primary_key=True)
    shared_access_id: Mapped[int] = mapped_column(ForeignKey("shared_access.id"), index=True)
    income_source_id: Mapped[int] = mapped_column(ForeignKey("income_sources.id"))

    shared_access: Mapped["SharedAccess"] = relationship(back_populates="shared_income")
    income_source: Mapped["IncomeSource"] = relationship()


class SavingsBucket(Base):
    __tablename__ = "savings_buckets"

    id: Mapped[int] = mapped_column(primary_key=True)
    user_id: Mapped[int] = mapped_column(ForeignKey("users.id"), index=True)
    name: Mapped[str] = mapped_column(String(255))  # e.g. "4th of July Trip", "Overall Savings"
    goal_amount: Mapped[Optional[float]] = mapped_column(Numeric(10, 2), nullable=True)

    entries: Mapped[list["SavingsEntry"]] = relationship(back_populates="bucket")


class SavingsEntry(Base):
    """A contribution to a savings bucket. `period_id` is null for a manual/initial
    balance entry (e.g. "I already have $15,000 saved") that isn't tied to any
    specific pay period -- mirrors how IncomeEntry.income_source_id works for
    one-time income."""

    __tablename__ = "savings_entries"

    id: Mapped[int] = mapped_column(primary_key=True)
    period_id: Mapped[Optional[int]] = mapped_column(ForeignKey("pay_periods.id"), nullable=True)
    bucket_id: Mapped[int] = mapped_column(ForeignKey("savings_buckets.id"))
    amount: Mapped[float] = mapped_column(Numeric(10, 2), default=0)
    note: Mapped[Optional[str]] = mapped_column(String(255), nullable=True)  # e.g. "Starting balance"
    created_at: Mapped[datetime.datetime] = mapped_column(default=datetime.datetime.utcnow)

    period: Mapped[Optional["PayPeriod"]] = relationship(back_populates="savings_entries")
    bucket: Mapped["SavingsBucket"] = relationship(back_populates="entries")


class Event(Base):
    """First-party product events (never sent to a third party): account
    created, onboarding completed, pay cycle managed. `data` is a small JSON
    string of details, e.g. {"days_after_payday": 2}."""

    __tablename__ = "events"

    id: Mapped[int] = mapped_column(primary_key=True)
    user_id: Mapped[Optional[int]] = mapped_column(nullable=True, index=True)
    name: Mapped[str] = mapped_column(String(50), index=True)
    data: Mapped[Optional[str]] = mapped_column(String(1000), nullable=True, default=None)
    created_at: Mapped[datetime.datetime] = mapped_column(default=datetime.datetime.utcnow)
